### ISSUE TITLE
實聯制

### ISSUE THREAD

**Issue by open0001** [gracotw/JiRenYao#1]
感恩提供方便的APP
但想請問是否有串接確診足跡的店家場所代碼&日期時間？
或者APP內有請USER要每天勤盯到過區域的衛生局公布資料？
否則原本具有雙向功能的實聯制看來僅剩下「當你確診時提供足跡」，是否容易成為黑數？

**Comment by gracotw** [comment]
簡訊實聯制今天已經取消. 這個 issue 可以關閉了. 回家吧.
